### ISSUE TITLE
kirby builder support for extends

### ISSUE THREAD

**Issue by bnomei** [jenstornell/kirby-blueprint-reader#14]
i must agree maybe stacking 4 levels of global field defs onto other is not a great idea but it's DRY, right? another problem might be `fieldsets` yaml section needed for kirby builder.

**page.yml with kirby builder (via extend)**
```yaml
...
fields:
  builder: builder
...
```

**fields/builder.yml defining kirby builder fieldsets (via extends again)**
```yaml
...
label: Builder
type: builder
fieldsets:
  # using 'extends' is required. will not work otherwise. 
  # see https://github.com/TimOetting/kirby-builder/issues/8
  fancyblock:
    extends: fancyblock
...
```

**fields/fancyblock.yml defining a single kirby builder fieldset fields (via extends again)**
```yaml
...
label: Fancyblock
snippet: blocks/fancyblock
fields:
  text:
    label: Text
    type: textarea
  colsize: colsize # finally the last extend
...
```
**fields/colsize.yml final extend step**
```yaml
label: Spaltenbreite
type: select
default: 'w-full'
options:
  w-full: 100%
  w-3_4: 75%
  w-2_3: 66%
  w-1_2: 50%
  w-1_3: 33%
  w-1_4: 25%
```

**in any template**
```php
print_r(b::blueprint('page', 'fields/builder/fieldsets/fancyblock')); 
// Array ( [extends] => fancyblock ), but not extended! 

echo b::blueprint('page', 'fields/builder/fieldsets/fancyblock/fields/colsize/options/'.$data->myfield()); 
// this is what i actually want but does not work
```
